config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :games do
        member do
          get 'roll_dice'
          get 'respond_to_property_purchase'
          get 'respond_to_income_tax'
        end
      end
      resources :board_spaces
      resources :players do 
        member do
          get 'pay_out_of_jail'
        end
      end
      resources :users
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  resources :games

  root 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :players
  has_many :games, :through => :players

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def show
    user = User.find_by_email(params[:email])

    if user.nil?
      render json: {}
    else
      render json:  user
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #TODO: use logged in user
    @user = User.find(params[:id])
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'User was successfully created.'
      redirect_to user_path @user
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to '/'
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.email %>!</h1>

<hr>

<h2>Games in Progress</h2>

<ul data-role="listview" data-inset="true" data-divider-theme="b">
	<% @user.games.each do |g| %>
		<li>
			<a href="<%= game_path(g) %>">
				<h3>Game with <%= g.players.map { |p| p.name }.join(', ') %></h3>
				<p><%= Player.find(g.current_player_id).name %>'s turn</p>
				<p class="ui-li-aside">Started on <%= g.created_at.strftime("%m/%d/%Y") %></p>
			</a>
		</li>
	<% end %>
</ul>

<!--
<h2>Game Invitations</h2>

<ul data-role="listview" data-inset="true" data-divider-theme="b">
<li><a href=""><h3>Invitation from [email]</h3><p>Sent at 12:04am</p></a></li>
</ul>
-->


<br><br>

<a href="<%= new_game_path %>" class="ui-btn ui-btn-b ui-corner-all">Create a New Game</a>